### ISSUE TITLE
バージョン管理システムの設定で選択肢の変更が適用されない

### ISSUE THREAD

**Issue by sk-ys** [ishikawa999/redmine_searchable_selectbox#4]
プロジェクトのバージョン管理システムの設定で選択肢の変更が適用されません．
現在 Redmine を使用している環境では Subversion を入れておらず，Git は入れているのですが，バージョン管理システムの選択を Git に変更しても初期選択肢の Subversion のコマンドが利用できない説明が残ってしまい，リポジトリの作成が出来ません．
プラグインを停止すると Git が使用出来ることを確認しています．

Ex. Git は使用出来るはずであるが，コマンドが利用できない説明が表示されたままとなる
![image](https://user-images.githubusercontent.com/963792/97121393-41509a00-1761-11eb-9368-8ba38123e12a.png)
↓ redmine_searchable_selectbox を停止すると，コマンドが利用できない説明は表示されない
![image](https://user-images.githubusercontent.com/963792/97121396-457cb780-1761-11eb-9285-dffcf97f9f7c.png)

よろしくお願いいします．

**Comment by ishikawa999** [comment]
@sk-ys 
問題を共有していただきありがとうございます。  
確認してみます。

**Comment by ishikawa999** [comment]
@sk-ys 

一時的な回避方法:
管理 > プラグイン > Redmine Searchable Selectbox の横の設定リンクを開き、  
Searchable selectboxを使用のチェックを外して適用ボタンを押すと一時的にセレクトボックスがすべて元の状態に戻ります。
この状態でGitリポジトリを作っていただき、すぐに元に戻せばとりあえずはリポジトリを作れると思います。

**Comment by sk-ys** [comment]
早速のご連絡ありがとうございます．よろしくお願いいたします．

**Comment by ishikawa999** [comment]
メモ:

'select[data-remote]'の要素の場合、値を変更したときにajaxがうまくトリガーできていないことが分かった。

以下のようなコードを適用すればselect2でもうまくトリガーできるようになりそうだが、メソッドの上書きはなるべく避けたいため、'select[data-remote]'の要素の場合はデフォルトのセレクトボックスのままにするという対応にする。
<details><summary>diff code</summary>
<p>

```diff
diff --git a/assets/javascripts/searchable_selectbox.js b/assets/javascripts/searchable_selectbox.js
index 02c4548..520e525 100644
--- a/assets/javascripts/searchable_selectbox.js
+++ b/assets/javascripts/searchable_selectbox.js
@@ -46,10 +46,10 @@ function replaceSelect2() {
     return;
   } else {
     var selectInTabular = $('.tabular select:not([multiple]):not(.select2-hidden-accessible)');
-    if (selectInTabular.length) { selectInTabular.select2({ width: '85%' }); }
+    if (selectInTabular.length) { selectInTabular.select2({ width: '85%' }).on('select2:select', function(){Rails.fire($(this)[0], 'change')}); }
 
     var other = $('select:not([multiple]):not(.select2-hidden-accessible)');
-    if (other.length) { other.select2(); }
+    if (other.length) { other.select2().on('select2:select', function(){Rails.fire($(this)[0], 'change')}); }
 
     var excludedSelect = $('table.list td>select');
     if (excludedSelect.length) { excludedSelect.select2('destroy'); }
diff --git a/init.rb b/init.rb
index 22f3192..1f2b12b 100644
--- a/init.rb
+++ b/init.rb
@@ -8,3 +8,13 @@ Redmine::Plugin.register :redmine_searchable_selectbox do
 
   settings default: {'enabled' => 1}, :partial => 'settings/searchable_selectbox_settings'
 end
+
+module RepositoriesHelperPatch
+  def scm_select_tag(repository)
+    super +
+    javascript_tag do
+      'replaceSelect2();'
+    end
+  end
+end
+RepositoriesHelper.prepend(RepositoriesHelperPatch)
\ No newline at end of file
```
</p>
</details>

**Comment by ishikawa999** [comment]
@sk-ys 
 
バージョン管理システムの設定などをはじめとした一部の形式のセレクトボックスについて対応が難しかったため、あまり綺麗な解決方法ではありませんがそれらについてのみプラグイン適応前のセレクトボックスのままにするよう変更いたしました。
最新のコードを適用していただけば、リポジトリの作成はできるようになると思います(検索は出来ません)。

**Comment by sk-ys** [comment]
迅速なご対応ありがとうございます．動作確認できました．
リポジトリの選択については，元々選択肢が少なく使用頻度も低いため通常のセレクトボックスで問題ないかと個人的には思いました．

**Comment by ishikawa999** [comment]
ご確認いただきありがとうございました 🙇
